export const tiposDeDocumentos = [
  'DNI/PASAPORTE (Anverso) Titular real',
  'DNI/PASAPORTE (Reverso) Titular real',
  'Certificado de titularidad de cuenta',
  'Recibo bancario',
  'Recibo autónomos o modelo 36/37',
  'DNI/PASAPORTE (Anverso) > 25%',
  'DNI/PASAPORTE (Reverso) > 25%',
  'DNI/PASAPORTE (Anverso) Administrador',
  'DNI/PASAPORTE (Reverso) Administrador',
  'Escrituras de apoderamiento',
  'Escrituras de Constitución y otras escrituras relevantes',
  'CIF',
  'Declaración responsable de vigencia de la documentación',
  'Certificado de estar al corriente de obligaciones tributarias',
  'Licencias de actividad',
  'Contrato PAYCOMET',
  'Documento SEPA',
  'Declaración operativa NO CES',
  'Formulario complementario de licencias',
  'Factura o recibo acreditativo de los servicios prestados',
  'Última declaración del IRPF y de IVA',
  'Estados financieros, declaraciones de IVA e Impuesto de Sociedades ejercicio anterior',
  'Tarjeta de identificación fiscal',
  'Escritura de poderes'
]

export const tiposDeDocumentosEnIngles = [
  'ID/PASSPORT (Front) Real Holder',
  'ID/PASSPORT (Back) Real Holder',
  'Account Ownership Certificate',
  'Bank Receipt',
  'Self-Employed Receipt or Model 36/37',
  'ID/PASSPORT (Front) > 25%',
  'ID/PASSPORT (Back) > 25%',
  'ID/PASSPORT (Front) Administrator',
  'ID/PASSPORT (Back) Administrator',
  'Power of Attorney Documents',
  'Constitution and Other Relevant Documents',
  'Tax Identification Number',
  'Declaration of Document Validity',
  'Certificate of Compliance with Tax Obligations',
  'Activity Licenses',
  'PAYCOMET Contract',
  'SEPA Document',
  'NO CES Operational Declaration',
  'Additional License Form',
  'Invoice or Receipt for Services Rendered',
  'Last IRPF and VAT Declaration',
  'Financial Statements, VAT and Corporation Tax Declarations for Previous Year',
  'Tax Identification Card',
  'Power of Attorney Document'
]
